### ISSUE TITLE
Json Decode Error In *.svelte

### ISSUE THREAD

**Issue by Epicccal** [4g3nt47/Striker#1]
Hello, I meet an error when installing the tool

I follow the installation guide in README, when i try to register, it return error.
<img width="874" alt="image" src="https://user-images.githubusercontent.com/34046030/216244366-4130abb3-a385-4085-a463-633352e3f7b6.png">

I never learned Javascript Before, but why use `res.json()` in *.svelte like this ?
![image](https://user-images.githubusercontent.com/34046030/216245019-376ab41d-4a6e-46d0-9a84-bb6fdbafeb3f.png)

I use `res` instead of `res.json` for all svelte file in the frontend

```bash
$ cd Striker/frontend
$ sed -i "s/res.json()/res/g" *.svelte
$ npm run build
$ cd dist
$ php -S 0.0.0.0:8888
```

Then i register again.
<img width="904" alt="image" src="https://user-images.githubusercontent.com/34046030/216246059-ebba5409-9d8d-4581-8f8a-0dd26676f164.png">

Its ok.
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/34046030/216246204-84daf660-e30f-4f83-ac9f-720b014e542f.png">

Also the simpleHttpServer In Python doesnt support 'POST' method, so i cant use `python3 -m http.server xxxx` for the frontend.
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/34046030/216247065-1fdeffc4-38b2-44c8-a022-a1a9e8cc2b26.png">

Thanks

**Comment by 4g3nt47** [comment]
Hi Epicccal!

Thanks a lot for the report, and very sorry for the late response.

I'm using `await res.json()` because I needed to access the `status` property returned in the json response by the backend API, which always returns a JSON response. I really wouldn't recommend removing it from the frontend components, they are all there for a reason.

From your error message it seems the response obtained is a HTML, probably because the value of `VITE_STRIKER_API` in your `frontend/.env` file is incorrect. Please make sure the backend (the Express API) is properly configured, and that your `VITE_STRIKER_API` is pointing to it.

As for the SimpleHTTPServer, you're confusing the frontend with the backend. You can absolutely use it to host the frontend because it doesn't need any POST request. All POST requests are made to the backend (which is powered by Express), not the frontend.

Thanks again.
